### ISSUE TITLE
Add service to send ping manually

### ISSUE THREAD

**Issue by eyalcha** [custom-components/healthchecksio#31]
Add service to allow send ping manually (e.g., can be use when home assistant starts)

**Comment by ludeeus** [comment]
Use the `homeassistant.update_entity` service.

**Comment by felipecrs** [comment]
> Use the `homeassistant.update_entity` service.

Are you sure it works? For me it doesn't do anything.

**Comment by felipecrs** [comment]
No matter how many times I call:
```yaml
service: homeassistant.update_entity
target:
  entity_id: binary_sensor.home_assistant
```

The events page on healthchecks.io doesn't show any new event, except by the automatic on every 5 minutes.
